/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-pages-json

interface NavigateToOptions {
  url: "/pages/define-page/async-function" |
       "/pages/define-page/function" |
       "/pages/define-page/import" |
       "/pages/define-page/nested-function" |
       "/pages/define-page/object" |
       "/pages/define-page/remove-console" |
       "/pages/define-page/yaml" |
       "/pages/index/index" |
       "/pages-sub/index" |
       "/pages-sub/about/index" |
       "/pages-sub/about/your";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/define-page/import" |
       "/pages/define-page/object";
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
